"""Rule-learning primitives shared across Cortex services (cortex-uo9b).

Teach-by-labeling: detect when a manual Gmail label change diverges from what
triage classified, and record it as a learning opportunity to propose a rule.
"""

from cortex_utils.learning.apply import (
    APPLY_QUEUE,
    ApplyJob,
    claim_proposal_apply_jobs,
    complete_apply_job,
    enqueue_proposal_apply,
    taught_mail_archived,
)
from cortex_utils.learning.expected_labels import (
    DEFAULT_LABEL_PREFIX,
    active_label_prefix,
    expected_cortex_labels,
    managed_labels,
)
from cortex_utils.learning.opportunities import (
    ADD,
    DIRECTIONS,
    REMOVE,
    ensure_learning_schema,
    record_learning_opportunity,
)
from cortex_utils.learning.proposals import (
    APPLIED,
    APPROVED,
    DEFERRED,
    FAILED,
    PENDING,
    REJECTED,
    SOURCE_TEACH,
    SUPERSEDED,
    ProposalRun,
    RuleProposal,
    approve_proposal,
    ensure_proposals_schema,
    get_proposal_by_id,
    get_proposal_by_message_id,
    list_pending_proposals,
    mark_proposal_applied,
    mark_proposal_deferred,
    mark_proposal_failed,
    mark_proposal_posted,
    propose_from_opportunities,
    reject_proposal,
    set_proposal_status,
    unposted_pending_proposals,
)

__all__ = [
    "DEFAULT_LABEL_PREFIX",
    "active_label_prefix",
    "expected_cortex_labels",
    "managed_labels",
    "ADD",
    "REMOVE",
    "DIRECTIONS",
    "ensure_learning_schema",
    "record_learning_opportunity",
    "PENDING",
    "APPROVED",
    "REJECTED",
    "SUPERSEDED",
    "APPLIED",
    "DEFERRED",
    "FAILED",
    "SOURCE_TEACH",
    "ProposalRun",
    "RuleProposal",
    "ensure_proposals_schema",
    "propose_from_opportunities",
    "list_pending_proposals",
    "unposted_pending_proposals",
    "get_proposal_by_message_id",
    "get_proposal_by_id",
    "mark_proposal_posted",
    "set_proposal_status",
    "approve_proposal",
    "reject_proposal",
    "mark_proposal_applied",
    "mark_proposal_deferred",
    "mark_proposal_failed",
    "APPLY_QUEUE",
    "ApplyJob",
    "enqueue_proposal_apply",
    "claim_proposal_apply_jobs",
    "complete_apply_job",
    "taught_mail_archived",
]
